### PR TITLE
Advance DOSGuard

### PR DESCRIPTION
**Pull request by undertome**
This small change does some minor refactoring and adds C++20 features.

---
This change is [Reviewable](https://reviewable.io/reviews/cjcobb23/clio/96)

### CODE REVIEW

**Comment by undertome** [comment]
The second commit resolves problems that resulted from treating warnings as errors.

**Comment by cjcobb23** [comment]
@legleux review the cmake stuff please

**Comment by cjcobb23** [comment]
@undertome can you rebase this onto master?

**Review by cjcobb23 — APPROVED** [review]
LGTM

**Pull request merged**
