### PR TITLE
Stop rebuilding everything everytime

### PR DESCRIPTION
**Pull request by legleux**
This at least prevents rebuilding everything all the time but something still seems wrong.

---
This change is [Reviewable](https://reviewable.io/reviews/cjcobb23/clio/73)

### CODE REVIEW

**Comment by cjcobb23** [comment]
what is still wrong?

**Comment by legleux** [comment]
> what is still wrong?

It feels like it still takes too long.

**Comment by cjcobb23** [comment]
> > what is still wrong?
> 
> It feels like it still takes too long.

Do you want to merge this as-is, or do you want to wait until you investigate more and figure out why it's still taking too long?

**Comment by cjcobb23** [comment]
Building gRPC takes forever. Is it still rebuilding gRPC every time?

**Pull request merged**
